name: libpen
version: 0.1.0
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: An ascii console display for dart-written roguelikes. Inspired heavily by libtcod and rot.js
dev_dependencies:
  browser: any
