name: libpen
version: 0.6.0-dev
author: Paul VanKeuren <paul.vankeuren@gmail.com>
description: An ascii console display for dart-written roguelikes. Inspired heavily by libtcod and rot.js
homepage: https://github.com/darkkiero/libpen
dependencies:
  piecemeal: "^0.2.0"
dev_dependencies:
  browser: any
  test: "^0.12.5+1"
